# Generated by Django 6.0.3 on 2026-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a mood name', max_length=30)),
                ('icon', models.CharField(help_text='Emoji representing the mood', max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
