# Generated by Django 6.0.3 on 2026-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique category name', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Describe this category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
